### ISSUE TITLE
Mount ro

### ISSUE THREAD

**Issue by hazcod** [jriguera/coreos-usb-creator#3]
Is the usb stick booted in read-only mode to preserve writes?

**Comment by jriguera** [comment]
It shouldn't (if you have created the usb image with the --usb  flag)

**Comment by hazcod** [comment]
Any plans to do this?
 (e.g. create a ramdisk and write the logs there)

**Comment by jriguera** [comment]
Sorry, I think I did not understand you.

When coreos boots it reads the FAT32 usb partition looking for the cloud-init configuration file, after that, when coreos is completely booted it is like a "live cd", everything is in memory and it won't write anything to disk nor usb.

**Comment by hazcod** [comment]
Ahh, I misunderstood. Thank you for explaining, I thought it would still write the logs to the usb/disk.
